/**
 * Completion command – Generate shell completion scripts for bash and zsh.
 *
 * Usage:
 *   wl completion bash        Print a bash completion script to stdout
 *   wl completion zsh         Print a zsh completion script to stdout
 *   wl completion             Show usage
 *   wl --json completion bash JSON output with shell and script fields
 */
// Commands that accept a work-item ID as their primary argument
const ID_ARG_COMMANDS = new Set([
    'show', 'update', 'delete', 'close', 'comment', 'dep', 'audit',
    'audit-show', 'audit-set', 'migrate',
]);
// Commands that accept a work-item ID as an optional argument
const OPTIONAL_ID_COMMANDS = new Set([
    'reviewed',
]);
function isShell(s) {
    return s === 'bash' || s === 'zsh';
}
function getCommandInfo(program) {
    const all = [];
    for (const cmd of program.commands || []) {
        const name = cmd.name();
        if (cmd.hidden || name === 'help' || name === 'completion')
            continue;
        const seen = new Set();
        const cmdOpts = [];
        // Collect global options first
        for (const opt of program.options || []) {
            const flag = opt.long || opt.short || '';
            if (flag && !seen.has(flag)) {
                cmdOpts.push(flag);
                seen.add(flag);
            }
        }
        // Collect command-specific options
        for (const opt of cmd.options || []) {
            const flag = opt.long || opt.short || '';
            if (flag && !seen.has(flag)) {
                cmdOpts.push(flag);
                seen.add(flag);
            }
        }
        // Add common options that Commander adds but might not be in options list
        for (const opt of ['--help', '-h']) {
            if (!seen.has(opt)) {
                cmdOpts.push(opt);
                seen.add(opt);
            }
        }
        cmdOpts.sort();
        all.push({
            name,
            aliases: cmd.aliases ? cmd.aliases() : [],
            description: cmd.description() || '',
            options: cmdOpts,
            takesIdArg: ID_ARG_COMMANDS.has(name),
            idArgOptional: OPTIONAL_ID_COMMANDS.has(name),
        });
    }
    all.sort((a, b) => a.name.localeCompare(b.name));
    return all;
}
/**
 * Generate a bash completion script.
 *
 * Builds the script line-by-line to avoid JavaScript template-literal
 * conflicts between JS `${...}` interpolation and bash `${...}` variables.
 */
function generateBashScript(cmdInfo) {
    const cmdNameStr = cmdInfo.map(c => c.name).join(' ');
    const idCmdStr = cmdInfo.filter(c => c.takesIdArg).map(c => c.name).join('|');
    const optIdCmdStr = cmdInfo.filter(c => c.idArgOptional).map(c => c.name).join('|');
    // Build the per-subcommand option branch lines
    const subcmdOptLines = [];
    for (const c of cmdInfo) {
        if (c.options.length === 0)
            continue;
        subcmdOptLines.push(`                ${c.name})
                    all_opts="${c.options.join(' ')}"
                    ;;`);
    }
    const subcmdOptBlock = subcmdOptLines.join('\n');
    const lines = [];
    lines.push('#/usr/bin/env bash');
    lines.push('# wl / worklog CLI bash completion script');
    lines.push('# Generated by "wl completion bash"');
    lines.push('#');
    lines.push('# Installation:');
    lines.push('#   source <(wl completion bash)          # temporary (current shell only)');
    lines.push('#   wl completion bash > ~/.wl-completion.bash && echo "source ~/.wl-completion.bash" >> ~/.bashrc');
    lines.push('');
    lines.push('_wl_completions() {');
    lines.push('    local cur prev words cword');
    lines.push('    _init_completion -n = || return');
    lines.push('');
    lines.push('    local all_cmds="' + cmdNameStr + ' completion"');
    lines.push('');
    lines.push('    # If the previous word is an option that takes a value, complete nothing');
    lines.push('    case $prev in');
    lines.push('        -F|--format|-n|--number|--prefix|--stage|--search|--assignee|--recency-policy|-g|--groups|--title|-t|--description|-d|--status|-s|--priority|-p|--issue-type|--parent|--tags|--comment|-c|--author|-a|--reason|-r|--tag)');
    lines.push('            return 0');
    lines.push('            ;;');
    lines.push('    esac');
    lines.push('');
    lines.push('    # If current word starts with -, complete options');
    lines.push('    if [[ "$cur" == -* ]]; then');
    lines.push('        local all_opts="--json --verbose --format --help --version -h -V -F -w --watch"');
    lines.push('');
    lines.push('        if [[ $cword -gt 1 ]]; then');
    lines.push('            local subcmd="${words[1]}"');
    lines.push('            case $subcmd in');
    lines.push(subcmdOptBlock);
    lines.push('            esac');
    lines.push('        fi');
    lines.push('');
    lines.push('        COMPREPLY=($(compgen -W "$all_opts" -- "$cur"))');
    lines.push('        return 0');
    lines.push('    fi');
    lines.push('');
    lines.push('    # Complete subcommands at the top level');
    lines.push('    if [[ $cword -eq 1 ]]; then');
    lines.push('        COMPREPLY=($(compgen -W "$all_cmds" -- "$cur"))');
    lines.push('        return 0');
    lines.push('    fi');
    lines.push('');
    lines.push('    # Dynamic completion for work-item IDs (position 2, after subcommand)');
    lines.push('    if [[ $cword -eq 2 ]]; then');
    lines.push('        local subcmd="${words[1]}"');
    lines.push('        case $subcmd in');
    lines.push('            ' + idCmdStr + '|' + optIdCmdStr + ')');
    lines.push('                local ids');
    lines.push('                ids=$(wl list --json 2>/dev/null | node -e "');
    lines.push('                    let d = \'\';');
    lines.push('                    process.stdin.on(\'data\', c => d += c);');
    lines.push('                    process.stdin.on(\'end\', () => {');
    lines.push('                        try {');
    lines.push('                            const p = JSON.parse(d);');
    lines.push('                            const items = p.workItems || p.results || [];');
    lines.push('                            items.forEach(i => { if (i.id && i.status !== \'closed\' && i.status !== \'completed\') process.stdout.write(i.id + \'\\n\'); });');
    lines.push('                        } catch(e) {}');
    lines.push('                    });');
    lines.push('                " 2>/dev/null)');
    lines.push('                COMPREPLY=($(compgen -W "$ids" -- "$cur"))');
    lines.push('                [[ -n $COMPREPLY ]] && return 0');
    lines.push('                ;;');
    lines.push('        esac');
    lines.push('    fi');
    lines.push('');
    lines.push('    # For completion subcommand, offer shell names');
    lines.push('    if [[ $cword -eq 2 ]] && [[ "${words[1]}" == "completion" ]]; then');
    lines.push('        COMPREPLY=($(compgen -W "bash zsh" -- "$cur"))');
    lines.push('        return 0');
    lines.push('    fi');
    lines.push('');
    lines.push('    # Fallback: complete file names');
    lines.push('    COMPREPLY=($(compgen -f -- "$cur"))');
    lines.push('} &&');
    lines.push('complete -F _wl_completions wl worklog');
    lines.push('');
    return lines.join('\n');
}
/**
 * Generate a zsh completion script using compdef and _arguments.
 */
function generateZshScript(cmdInfo) {
    const idCmds = cmdInfo.filter(c => c.takesIdArg).map(c => c.name);
    const optionalIdCmds = cmdInfo.filter(c => c.idArgOptional).map(c => c.name);
    const cmdValueLines = cmdInfo.map(c => `                ${c.name} \\`).join('\n');
    // Build case branches for commands
    const argBranches = [];
    // Completion subcommand
    argBranches.push('                completion)');
    argBranches.push("                    _arguments '1: :(bash zsh)'");
    argBranches.push('                    ;;');
    // Commands that accept a work-item ID
    for (const name of [...idCmds, ...optionalIdCmds]) {
        argBranches.push('                ' + name + ')');
        argBranches.push('                    _arguments \\');
        argBranches.push("                        ':work-item-id: _wl_ids' \\");
        argBranches.push("                        '--json[output in JSON format]' \\");
        argBranches.push("                        '--verbose[enable verbose output]' \\");
        argBranches.push("                        '--format=[output format]:format:(concise normal full raw markdown text plain auto)' \\");
        argBranches.push("                        '--help[display help]' \\");
        argBranches.push("                        '--version[display version]'");
        argBranches.push('                    ;;');
    }
    // Other commands (no ID arg)
    for (const c of cmdInfo) {
        if (c.takesIdArg || c.idArgOptional)
            continue;
        argBranches.push('                ' + c.name + ')');
        argBranches.push('                    _arguments \\');
        argBranches.push("                        '--json[output in JSON format]' \\");
        argBranches.push("                        '--verbose[enable verbose output]' \\");
        argBranches.push("                        '--format=[output format]:format:(concise normal full raw markdown text plain auto)' \\");
        argBranches.push("                        '--help[display help]' \\");
        argBranches.push("                        '--version[display version]'");
        argBranches.push('                    ;;');
    }
    argBranches.push('                *)');
    argBranches.push('                    _default');
    argBranches.push('                    ;;');
    const argBlock = argBranches.join('\n');
    const lines = [];
    lines.push('#compdef wl worklog');
    lines.push('# wl / worklog CLI zsh completion script');
    lines.push('# Generated by "wl completion zsh"');
    lines.push('#');
    lines.push('# Installation:');
    lines.push('#   source <(wl completion zsh)           # temporary (current shell only)');
    lines.push('#   wl completion zsh > ~/.wl-completion.zsh && echo "source ~/.wl-completion.zsh" >> ~/.zshrc');
    lines.push('');
    lines.push('_wl_ids() {');
    lines.push('    local ids');
    lines.push('    ids=$(wl list --json 2>/dev/null | node -e "');
    lines.push("        let d = '';");
    lines.push("        process.stdin.on('data', c => d += c);");
    lines.push("        process.stdin.on('end', () => {");
    lines.push('            try {');
    lines.push('                const p = JSON.parse(d);');
    lines.push('                const items = p.workItems || p.results || [];');
    lines.push("                items.forEach(i => { if (i.id && i.status !== 'closed' && i.status !== 'completed') process.stdout.write(i.id + '\\n'); });");
    lines.push('            } catch(e) {}');
    lines.push('        });');
    lines.push('    " 2>/dev/null)');
    lines.push('    _values "work item id" $(echo "$ids")');
    lines.push('}');
    lines.push('');
    lines.push('_wl() {');
    lines.push('    local curcontext="$curcontext" state line');
    lines.push('    typeset -A opt_args');
    lines.push('');
    lines.push('    _arguments -C \\');
    lines.push("        '--json[output in JSON format]' \\");
    lines.push("        '--verbose[enable verbose output]' \\");
    lines.push("        '--format=[output format]:format:(concise normal full raw markdown text plain auto)' \\");
    lines.push("        '--help[display help]' \\");
    lines.push("        '--version[display version]' \\");
    lines.push("        '(-h --help){-h,--help}[display help]' \\");
    lines.push("        '(-V --version){-V,--version}[display version]' \\");
    lines.push("        '(-w --watch){-w,--watch}[watch mode]' \\");
    lines.push("        '1: :->cmds' \\");
    lines.push("        '*::arg:->args'");
    lines.push('');
    lines.push('    case $state in');
    lines.push('        cmds)');
    lines.push("            _values 'wl commands' \\");
    lines.push(cmdValueLines);
    lines.push("                'help[display help for command]'");
    lines.push('            ;;');
    lines.push('        args)');
    lines.push('            case $words[1] in');
    lines.push(argBlock);
    lines.push('            esac');
    lines.push('            ;;');
    lines.push('    esac');
    lines.push('}');
    lines.push('');
    lines.push('compdef _wl wl worklog');
    lines.push('');
    return lines.join('\n');
}
export default function register(ctx) {
    const { program, output, utils } = ctx;
    program
        .command('completion')
        .description('Generate shell completion scripts for bash and zsh')
        .argument('[shell]', 'Target shell (bash or zsh)')
        .action((shell) => {
        const jsonMode = utils.isJsonMode();
        if (!shell) {
            if (jsonMode) {
                output.json({
                    success: true,
                    note: 'Available shells: bash, zsh. Usage: wl completion <shell>',
                    availableShells: ['bash', 'zsh'],
                });
            }
            else {
                console.log('Usage: wl completion <shell>');
                console.log('');
                console.log('Generate shell completion scripts for the wl CLI.');
                console.log('');
                console.log('Available shells:');
                console.log('  bash  Generate bash completion script');
                console.log('  zsh   Generate zsh completion script');
                console.log('');
                console.log('Examples:');
                console.log('  wl completion bash    # Output bash completion script');
                console.log('  wl completion zsh     # Output zsh completion script');
                console.log('');
                console.log('Installation:');
                console.log('  Bash:  source <(wl completion bash)');
                console.log('  Zsh:   source <(wl completion zsh)');
                console.log('');
                console.log('To make permanent, add the source command to your ~/.bashrc or ~/.zshrc.');
            }
            return;
        }
        if (!isShell(shell)) {
            if (jsonMode) {
                output.error(`Unknown shell: "${shell}". Supported shells: bash, zsh`, {
                    success: false,
                    error: `Unknown shell: "${shell}"`,
                    supportedShells: ['bash', 'zsh'],
                });
            }
            else {
                console.error(`Unknown shell: "${shell}". Supported shells: bash, zsh`);
            }
            process.exit(1);
            return;
        }
        // Introspect commands from the Commander program
        const commands = getCommandInfo(program);
        let script;
        if (shell === 'bash') {
            script = generateBashScript(commands);
        }
        else {
            script = generateZshScript(commands);
        }
        if (jsonMode) {
            output.json({
                success: true,
                shell,
                script,
                commandCount: commands.length,
            });
        }
        else {
            process.stdout.write(script);
        }
    });
}
//# sourceMappingURL=completion.js.map